---

- name: Include prepare tasks
  ansible.builtin.include_tasks: 'prepare.yml'

- name: Include configure tasks
  ansible.builtin.include_tasks: 'configure.yml'

- name: Include install tasks
  ansible.builtin.include_tasks: 'install.yml'

- name: Flush handlers before tests
  ansible.builtin.meta: flush_handlers

- name: Include test tasks
  ansible.builtin.include_tasks: 'test.yml'
