---
- name: restart_web3siger
  ansible.builtin.service:
    name: "{{ web3signer_service_name }}"
    state: restarted
    enabled: True
    daemon_reload: True
  become: True
  tags:
    - skip_ansible_lint
