name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: install dependencies
        run: |
          python3 -m venv .venv
          . .venv/bin/activate
          pip3 install -r requirements.txt
          
      - name: Run Tests
        run: |
          . .venv/bin/activate
          ansible-lint . **/*.yml -c test/lint/.ansible-lint